//! Portal — platform services (Tags + Files) served over ConnectRPC.
//!
//! Message types are generated by `buffa` and service stubs by `connect-rust`
//! (see `buf.gen.yaml`). Generated code is committed under `src/generated/`;
//! regenerate with `just portal-gen` after editing the protos.

// Handlers implement the generated service traits with plain `async fn`, whose
// concrete return types refine the trait's `impl Encodable + Send` — the
// idiomatic pattern for connect-rust services.
#![allow(refining_impl_trait)]

pub mod generated {
    /// buffa-generated message types (owned structs + zero-copy views).
    #[path = "buffa/mod.rs"]
    pub mod buffa;
    /// connect-rust-generated service traits, dispatchers, and clients.
    #[path = "connect/mod.rs"]
    pub mod connect;
}

pub mod config;
pub mod error;
pub mod service;
pub mod store;

/// Convenience re-exports for the generated message and service trees.
pub use generated::buffa::portal as proto;
pub use generated::connect::portal as services;
