import type { components } from "./uc-api";

// The OpenAPI surface (paths + raw components) generated by openapi-typescript
// from openapi/unity-catalog.yaml (the OSS Unity Catalog REST API, which is what
// the server in environments/ serves). Regenerate with `npm run gen:api`.
export type { components, paths } from "./uc-api";

type Schemas = components["schemas"];

/** A Unity Catalog catalog (top level of the three-level namespace). */
export type CatalogInfo = Schemas["CatalogInfo"];

/** A Unity Catalog schema (second level), child of a catalog. */
export type SchemaInfo = Schemas["SchemaInfo"];

/** A Unity Catalog table (third level), including its column definitions. */
export type TableInfo = Schemas["TableInfo"];

/** A single column of a table. */
export type ColumnInfo = Schemas["ColumnInfo"];

export type ListCatalogsResponse = Schemas["ListCatalogsResponse"];
export type ListSchemasResponse = Schemas["ListSchemasResponse"];
export type ListTablesResponse = Schemas["ListTablesResponse"];
