//! Artifact generation: a [`ResolvedGraph`] → a runnable Docker Compose file.
//!
//! Kept separate from resolution ([`crate::resolve`]) so the analysis stays pure
//! and reusable. Generation is *also* pure: it takes a graph and a
//! [`LaunchContext`] (the host-side facts — the UC port, paths) and returns
//! string/struct artifacts. The desktop crate owns the side effects (writing the
//! file, running `docker compose`, spawning uvx).
//!
//! The generated compose file `include:`s the self-contained desktop fragments
//! under `environments/services/desktop/` — written specifically for this stack,
//! so there are no cross-stack defaults, profiles, or contradictory credentials
//! to override. The single boundary value the generator supplies is the **UC host
//! URL**, injected outward (Docker→UC) for any module that consumes it; marimo
//! (uvx) gets `UC_URI` instead (see [`uvx_uc_uri`]).

use std::collections::BTreeMap;

use crate::resolve::ResolvedGraph;

/// Host-side facts needed to turn a graph into runnable artifacts. The desktop
/// crate fills this in at start time (the UC sidecar's resolved port; the
/// resolved `environments/` paths).
#[derive(Clone, Debug)]
pub struct LaunchContext {
    /// The Unity Catalog host port the sidecar bound to. Injected outward so
    /// Docker services reach UC at `host.docker.internal:<uc_port>` and uvx
    /// sidecars at `localhost:<uc_port>`. `None` when UC is disabled.
    pub uc_port: Option<u16>,
    /// Absolute path to `environments/services/desktop/`, where the self-contained
    /// desktop fragments live. The generated compose `include:`s fragments here.
    pub fragments_dir: String,
    /// Absolute path to `environments/` — the `project_directory` the included
    /// fragments resolve their relative `./.data`, `./config`, `./docker` paths
    /// against.
    pub environments_dir: String,
}

/// The generated, runnable artifacts for an environment's Docker modules.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ComposeArtifacts {
    /// The generated top-level compose file contents (`include:`s the desktop
    /// fragments). Empty when the graph has no Docker modules.
    pub compose_yaml: String,
    /// Environment variables to pass to `docker compose` (the values the fragments
    /// interpolate, including the UC host URL). Empty when no Docker modules.
    pub env: BTreeMap<String, String>,
}

/// The UC URL injected into Docker services (reached across the host boundary).
fn docker_uc_url(uc_port: u16) -> String {
    format!("http://host.docker.internal:{uc_port}/api/2.1/unity-catalog/")
}

/// The UC URL injected into uvx sidecars (host-local).
pub fn uvx_uc_uri(uc_port: u16) -> String {
    format!("http://localhost:{uc_port}/api/2.1/unity-catalog/")
}

/// Generate the Docker Compose artifacts for a graph. Returns empty artifacts
/// when the graph has no Docker modules (a marimo-only environment needs none).
pub fn generate_compose(graph: &ResolvedGraph, ctx: &LaunchContext) -> ComposeArtifacts {
    let docker = graph.docker_modules();
    if docker.is_empty() {
        return ComposeArtifacts {
            compose_yaml: String::new(),
            env: BTreeMap::new(),
        };
    }

    // The one boundary value: the UC host URL, injected outward. The desktop
    // fragments otherwise carry their own (desktop-specific) configuration, so
    // there is nothing else to override here.
    let mut env = BTreeMap::new();
    if let Some(port) = ctx.uc_port {
        env.insert("UC_HOST_URL".to_string(), docker_uc_url(port));
    }

    // Generated top-level file: just `include:`s each module's self-contained
    // desktop fragment, all sharing the `environments/` project directory so
    // their relative paths resolve. Hand-built YAML (a tiny, fixed shape) rather
    // than pulling in a YAML serializer dependency.
    let mut yaml = String::from("# Generated by env-modules — do not edit.\n");
    yaml.push_str("name: ${COMPOSE_PROJECT_NAME}\n\n");
    yaml.push_str("include:\n");
    for module in &docker {
        if let crate::model::ModuleKind::DockerService { fragment } = &module.kind {
            yaml.push_str(&format!("  - path: {}/{}\n", ctx.fragments_dir, fragment));
            yaml.push_str(&format!(
                "    project_directory: {}\n",
                ctx.environments_dir
            ));
        }
    }

    ComposeArtifacts {
        compose_yaml: yaml,
        env,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::resolve::resolve;

    fn ctx() -> LaunchContext {
        LaunchContext {
            uc_port: Some(54321),
            fragments_dir: "/repo/environments/services/desktop".into(),
            environments_dir: "/repo/environments".into(),
        }
    }

    #[test]
    fn marimo_only_generates_no_compose() {
        let graph = resolve(&["marimo".into()]).unwrap();
        let artifacts = generate_compose(&graph, &ctx());
        assert!(artifacts.compose_yaml.is_empty());
        assert!(artifacts.env.is_empty());
    }

    #[test]
    fn mlflow_includes_fragments_and_injects_uc_url() {
        let graph = resolve(&["mlflow".into()]).unwrap();
        let artifacts = generate_compose(&graph, &ctx());
        // Includes each docker fragment from the desktop dir.
        for fragment in ["mlflow.yaml", "postgres.yaml", "azurite.yaml", "envoy.yaml"] {
            assert!(
                artifacts
                    .compose_yaml
                    .contains(&format!("services/desktop/{fragment}")),
                "expected include of desktop/{fragment} in:\n{}",
                artifacts.compose_yaml
            );
        }
        // All includes share the environments/ project directory.
        assert!(artifacts.compose_yaml.contains("project_directory: /repo/environments\n"));
        // Injects the UC host URL pointing at host.docker.internal.
        assert_eq!(
            artifacts.env.get("UC_HOST_URL").map(String::as_str),
            Some("http://host.docker.internal:54321/api/2.1/unity-catalog/")
        );
    }

    #[test]
    fn uvx_uc_uri_is_localhost() {
        assert_eq!(
            uvx_uc_uri(54321),
            "http://localhost:54321/api/2.1/unity-catalog/"
        );
    }
}
